---
hosts:
  webassets:
    hostname: webassets.confederationcollege.ca
    actions:
      - ping
      - httpcheck:
          endpoint: https://webassets.confederationcollege.ca
      - cert_expiration:
          endpoint: webassets.confederationcollege.ca
          expiration_warning_days: 30
  secureassets:
    hostname: secureassets.confederationcollege.ca
    actions:
      - ping
  cognos-test:
    hostname: cc-cognotest-01.confederationc.on.ca
    actions:
      - ping
      - cert_expiration:
          endpoint: cc-cognotest-01.confederationc.on.ca:9300
          expiration_warning_days: 30
  Solarwinds Service Desk:
    hostname: itsupport.confederationcollege.ca
    actions:
      - ping
  Aruba Mobility Conductor:
    hostname: aruba.confederationcollege.ca
    port: 4343
    actions:
      - ping
  cc-aruba-7210-01:
    hostname: cc-aruba-7210-01.confederationcollege.ca
    port: 4343
    actions:
      - ping
  cc-aruba-7210-02:
    hostname: cc-aruba-7210-02.confederationcollege.ca
    port: 4343
    actions:
      - ping
  barracuda:
    hostname: barracuda.confederationcollege.ca
    inbound_decrypt: yes
    proxy: yes
    actions:
      - ping
  Maintenance Connection:
    hostname: facilitymaint.confederationcollege.ca
    server: cc-apps-01
    actions:
      - ping
  Gitlab:
    hostname: cc-gitlab.confederationcollege.ca
    actions:
      - cert_expiration:
          endpoint: cc-gitlab.confederationcollege.ca
          expiration_warning_days: 30
